spring:
  application:
    name: SecurityPart2
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:8889/security-2}
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  output:
    ansi:
      enabled: ALWAYS